import { createClient } from '@/lib/supabase/client';
import { Project, ProjectFeature, ProjectSection } from '@/lib/types/database';

const supabase = createClient();

export interface ProjectFormData {
  title: string;
  subtitle: string;
  tagline?: string;
  main_image?: string;
  tags: string[];
  live_url: string;
  services: string;
  categories: string;
  is_active: boolean;
  sections: Array<ProjectSection>;
  features: Array<ProjectFeature>;
}

/**
 * Upload image to Supabase storage
 */
export const uploadProjectImage = async (
  file: File,
  projectId: string
): Promise<string> => {
  const fileExt = file.name.split('.').pop();
  // Generate a unique suffix per file:
  const uniqueSuffix =
    // in modern browsers / Node:
    typeof crypto !== 'undefined' && 'randomUUID' in crypto
      ? crypto.randomUUID()
      : Math.random().toString(36).substring(2, 10);

  // Now filenames will never collide:
  const fileName = `${projectId}-${uniqueSuffix}.${fileExt}`;
  const filePath = `projects/${fileName}`;

  const { data, error } = await supabase.storage
    .from('lordevs')
    .upload(filePath, file, {
      cacheControl: '3600',
      upsert: false, // still false so you get errors if you really duplicate––but names now unique
    });

  if (error) throw error;

  const {
    data: { publicUrl },
  } = supabase.storage.from('lordevs').getPublicUrl(data.path);

  return publicUrl;
};

/**
 * Delete image from Supabase storage
 */
export const deleteProjectImage = async (imageUrl: string): Promise<void> => {
  // Extract file path from URL
  const urlParts = imageUrl.split('/');
  const fileName = urlParts[urlParts.length - 1];
  const filePath = `projects/${fileName}`;

  const { error } = await supabase.storage.from('lordevs').remove([filePath]);

  if (error) {
    throw error;
  }
};

/**
 * Create a new project
 */
export const createProject = async (
  formData: ProjectFormData,
  imageFile?: File
): Promise<Project> => {
  let imageUrl = '';

  // Generate temporary ID for image upload
  const tempId = Date.now().toString();

  // Upload image if provided
  if (imageFile) {
    imageUrl = await uploadProjectImage(imageFile, tempId);
  }

  // Prepare project data (slug will be generated by database trigger)
  const projectData = {
    title: formData.title,
    subtitle: formData.subtitle,
    tagline: formData.tagline || null,
    services: formData.services,
    categories: formData.categories,
    tags: formData.tags,
    main_image: imageUrl,
    live_url: formData.live_url || null,
    is_active: formData.is_active,
    sections: formData.sections.length > 0 ? formData.sections : [],
    features: formData.features.length > 0 ? formData.features : [],
    order_index: 0,
  };

  // Insert project into database
  const { data, error } = await supabase
    .from('projects')
    .insert([projectData])
    .select()
    .single();

  if (error) {
    // Clean up uploaded image if project creation fails
    if (imageUrl) {
      try {
        await deleteProjectImage(imageUrl);
      } catch (cleanupError) {
        console.error('Failed to cleanup image:', cleanupError);
      }
    }
    throw error;
  }

  return data;
};

/**
 * Update an existing project
 */
export const updateProject = async (
  projectId: string,
  formData: ProjectFormData,
  imageFile?: File,
  currentImageUrl?: string
): Promise<Project> => {
  let imageUrl = currentImageUrl || '';

  // Upload new image if provided
  if (imageFile) {
    // Delete old image if it exists
    if (currentImageUrl) {
      try {
        await deleteProjectImage(currentImageUrl);
      } catch (error) {
        console.error('Failed to delete old image:', error);
      }
    }

    // Upload new image
    imageUrl = await uploadProjectImage(imageFile, projectId);
  }

  // Prepare update data (slug will be updated by database trigger if title changed)
  const updateData = {
    title: formData.title,
    subtitle: formData.subtitle,
    tagline: formData.tagline || null,
    services: formData.services,
    categories: formData.categories,
    tags: formData.tags,
    main_image: imageUrl,
    live_url: formData.live_url || null,
    is_active: formData.is_active,
    sections: formData.sections.length > 0 ? formData.sections : [],
    features: formData.features.length > 0 ? formData.features : [],
    updated_at: new Date().toISOString(),
  };

  // Update project in database
  const { data, error } = await supabase
    .from('projects')
    .update(updateData)
    .eq('id', projectId)
    .select()
    .single();

  if (error) {
    // Clean up uploaded image if project update fails
    if (imageFile && imageUrl !== currentImageUrl) {
      try {
        await deleteProjectImage(imageUrl);
      } catch (cleanupError) {
        console.error('Failed to cleanup image:', cleanupError);
      }
    }
    throw error;
  }

  return data;
};

/**
 * Get project by ID
 */
export const getProjectById = async (projectId: string): Promise<Project> => {
  const { data, error } = await supabase
    .from('projects')
    .select('*')
    .eq('id', projectId)
    .single();

  if (error) {
    throw error;
  }

  return data;
};

/**
 * Delete a project
 */
export const deleteProject = async (projectId: string): Promise<void> => {
  // Get project to access image URL
  const project = await getProjectById(projectId);

  // Delete image from storage if it exists
  if (project.main_image) {
    try {
      await deleteProjectImage(project.main_image);
    } catch (error) {
      console.error('Failed to delete project image:', error);
    }
  }

  // Delete project from database
  const { error } = await supabase
    .from('projects')
    .delete()
    .eq('id', projectId);

  if (error) {
    throw error;
  }
};

/**
 * Get all projects with optional filtering
 */
export const getProjects = async (filters?: {
  category?: string;
  isActive?: boolean;
  searchTerm?: string;
}): Promise<Project[]> => {
  let query = supabase
    .from('projects')
    .select('*')
    .order('created_at', { ascending: false });

  // Apply filters
  if (filters?.category) {
    query = query.eq('category', filters.category);
  }

  if (filters?.isActive !== undefined) {
    query = query.eq('is_active', filters.isActive);
  }

  if (filters?.searchTerm) {
    query = query.or(
      `title.ilike.%${filters.searchTerm}%,subtitle.ilike.%${filters.searchTerm}%`
    );
  }

  const { data, error } = await query;

  if (error) {
    throw error;
  }

  return data || [];
};

/**
 * Get active projects
 */
export const getActiveProjects = async (): Promise<Project[]> => {
  const { data, error } = await supabase
    .from('projects')
    .select('*')
    .eq('is_active', true)
    .order('created_at', { ascending: false });

  if (error) {
    throw error;
  }

  return data || [];
};

/**
 * Get a project by its slug
 */
export const getProjectBySlug = async (
  slug: string
): Promise<Project | null> => {
  const { data, error } = await supabase
    .from('projects')
    .select('*')
    .eq('project_slug', slug)
    .eq('is_active', true)
    .single();

  if (error) {
    console.error('Error fetching project by slug:', error);
    return null;
  }

  return data;
};
