export interface FlagData {
  code: string;
  name: string;
  emoji: string;
  unicode: string;
  continent: string;
  region?: string;
  tags?: string[];
}

export const flagsData: FlagData[] = [
  // North America
  {
    code: 'US',
    name: 'United States',
    emoji: '🇺🇸',
    unicode: 'U+1F1FA U+1F1F8',
    continent: 'North America',
    tags: ['usa', 'america', 'united states'],
  },
  {
    code: 'CA',
    name: 'Canada',
    emoji: '🇨🇦',
    unicode: 'U+1F1E8 U+1F1E6',
    continent: 'North America',
    tags: ['canada', 'canadian'],
  },
  {
    code: 'MX',
    name: 'Mexico',
    emoji: '🇲🇽',
    unicode: 'U+1F1F2 U+1F1FD',
    continent: 'North America',
    tags: ['mexico', 'mexican'],
  },

  // Europe
  {
    code: 'GB',
    name: 'United Kingdom',
    emoji: '🇬🇧',
    unicode: 'U+1F1EC U+1F1E7',
    continent: 'Europe',
    tags: ['uk', 'britain', 'england', 'scotland', 'wales'],
  },
  {
    code: 'DE',
    name: 'Germany',
    emoji: '🇩🇪',
    unicode: 'U+1F1E9 U+1F1EA',
    continent: 'Europe',
    tags: ['germany', 'german', 'deutschland'],
  },
  {
    code: 'FR',
    name: 'France',
    emoji: '🇫🇷',
    unicode: 'U+1F1EB U+1F1F7',
    continent: 'Europe',
    tags: ['france', 'french'],
  },
  {
    code: 'IT',
    name: 'Italy',
    emoji: '🇮🇹',
    unicode: 'U+1F1EE U+1F1F9',
    continent: 'Europe',
    tags: ['italy', 'italian'],
  },
  {
    code: 'ES',
    name: 'Spain',
    emoji: '🇪🇸',
    unicode: 'U+1F1EA U+1F1F8',
    continent: 'Europe',
    tags: ['spain', 'spanish'],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    emoji: '🇳🇱',
    unicode: 'U+1F1F3 U+1F1F1',
    continent: 'Europe',
    tags: ['netherlands', 'dutch', 'holland'],
  },
  {
    code: 'PL',
    name: 'Poland',
    emoji: '🇵🇱',
    unicode: 'U+1F1F5 U+1F1F1',
    continent: 'Europe',
    tags: ['poland', 'polish'],
  },
  {
    code: 'RU',
    name: 'Russia',
    emoji: '🇷🇺',
    unicode: 'U+1F1F7 U+1F1FA',
    continent: 'Europe',
    tags: ['russia', 'russian'],
  },
  {
    code: 'CH',
    name: 'Switzerland',
    emoji: '🇨🇭',
    unicode: 'U+1F1E8 U+1F1ED',
    continent: 'Europe',
    tags: ['switzerland', 'swiss'],
  },
  {
    code: 'AT',
    name: 'Austria',
    emoji: '🇦🇹',
    unicode: 'U+1F1E6 U+1F1F9',
    continent: 'Europe',
    tags: ['austria', 'austrian'],
  },
  {
    code: 'BE',
    name: 'Belgium',
    emoji: '🇧🇪',
    unicode: 'U+1F1E7 U+1F1EA',
    continent: 'Europe',
    tags: ['belgium', 'belgian'],
  },
  {
    code: 'DK',
    name: 'Denmark',
    emoji: '🇩🇰',
    unicode: 'U+1F1E9 U+1F1F0',
    continent: 'Europe',
    tags: ['denmark', 'danish'],
  },
  {
    code: 'FI',
    name: 'Finland',
    emoji: '🇫🇮',
    unicode: 'U+1F1EB U+1F1EE',
    continent: 'Europe',
    tags: ['finland', 'finnish'],
  },
  {
    code: 'NO',
    name: 'Norway',
    emoji: '🇳🇴',
    unicode: 'U+1F1F3 U+1F1F4',
    continent: 'Europe',
    tags: ['norway', 'norwegian'],
  },
  {
    code: 'SE',
    name: 'Sweden',
    emoji: '🇸🇪',
    unicode: 'U+1F1F8 U+1F1EA',
    continent: 'Europe',
    tags: ['sweden', 'swedish'],
  },
  {
    code: 'PT',
    name: 'Portugal',
    emoji: '🇵🇹',
    unicode: 'U+1F1F5 U+1F1F9',
    continent: 'Europe',
    tags: ['portugal', 'portuguese'],
  },
  {
    code: 'IE',
    name: 'Ireland',
    emoji: '🇮🇪',
    unicode: 'U+1F1EE U+1F1EA',
    continent: 'Europe',
    tags: ['ireland', 'irish'],
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    emoji: '🇨🇿',
    unicode: 'U+1F1E8 U+1F1FF',
    continent: 'Europe',
    tags: ['czech', 'czechia'],
  },
  {
    code: 'GR',
    name: 'Greece',
    emoji: '🇬🇷',
    unicode: 'U+1F1EC U+1F1F7',
    continent: 'Europe',
    tags: ['greece', 'greek'],
  },

  // Asia
  {
    code: 'CN',
    name: 'China',
    emoji: '🇨🇳',
    unicode: 'U+1F1E8 U+1F1F3',
    continent: 'Asia',
    tags: ['china', 'chinese'],
  },
  {
    code: 'JP',
    name: 'Japan',
    emoji: '🇯🇵',
    unicode: 'U+1F1EF U+1F1F5',
    continent: 'Asia',
    tags: ['japan', 'japanese'],
  },
  {
    code: 'KR',
    name: 'South Korea',
    emoji: '🇰🇷',
    unicode: 'U+1F1F0 U+1F1F7',
    continent: 'Asia',
    tags: ['korea', 'korean', 'south korea'],
  },
  {
    code: 'IN',
    name: 'India',
    emoji: '🇮🇳',
    unicode: 'U+1F1EE U+1F1F3',
    continent: 'Asia',
    tags: ['india', 'indian'],
  },
  {
    code: 'ID',
    name: 'Indonesia',
    emoji: '🇮🇩',
    unicode: 'U+1F1EE U+1F1E9',
    continent: 'Asia',
    tags: ['indonesia', 'indonesian'],
  },
  {
    code: 'TH',
    name: 'Thailand',
    emoji: '🇹🇭',
    unicode: 'U+1F1F9 U+1F1ED',
    continent: 'Asia',
    tags: ['thailand', 'thai'],
  },
  {
    code: 'VN',
    name: 'Vietnam',
    emoji: '🇻🇳',
    unicode: 'U+1F1FB U+1F1F3',
    continent: 'Asia',
    tags: ['vietnam', 'vietnamese'],
  },
  {
    code: 'MY',
    name: 'Malaysia',
    emoji: '🇲🇾',
    unicode: 'U+1F1F2 U+1F1FE',
    continent: 'Asia',
    tags: ['malaysia', 'malaysian'],
  },
  {
    code: 'SG',
    name: 'Singapore',
    emoji: '🇸🇬',
    unicode: 'U+1F1F8 U+1F1EC',
    continent: 'Asia',
    tags: ['singapore', 'singaporean'],
  },
  {
    code: 'PH',
    name: 'Philippines',
    emoji: '🇵🇭',
    unicode: 'U+1F1F5 U+1F1ED',
    continent: 'Asia',
    tags: ['philippines', 'filipino'],
  },
  {
    code: 'PK',
    name: 'Pakistan',
    emoji: '🇵🇰',
    unicode: 'U+1F1F5 U+1F1F0',
    continent: 'Asia',
    tags: ['pakistan', 'pakistani'],
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    emoji: '🇧🇩',
    unicode: 'U+1F1E7 U+1F1E9',
    continent: 'Asia',
    tags: ['bangladesh', 'bangladeshi'],
  },
  {
    code: 'TR',
    name: 'Turkey',
    emoji: '🇹🇷',
    unicode: 'U+1F1F9 U+1F1F7',
    continent: 'Asia',
    tags: ['turkey', 'turkish'],
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    emoji: '🇸🇦',
    unicode: 'U+1F1F8 U+1F1E6',
    continent: 'Asia',
    tags: ['saudi', 'saudi arabia'],
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    emoji: '🇦🇪',
    unicode: 'U+1F1E6 U+1F1EA',
    continent: 'Asia',
    tags: ['uae', 'emirates', 'dubai'],
  },
  {
    code: 'IL',
    name: 'Israel',
    emoji: '🇮🇱',
    unicode: 'U+1F1EE U+1F1F1',
    continent: 'Asia',
    tags: ['israel', 'israeli'],
  },
  {
    code: 'LB',
    name: 'Lebanon',
    emoji: '🇱🇧',
    unicode: 'U+1F1F1 U+1F1E7',
    continent: 'Asia',
    tags: ['lebanon', 'lebanese'],
  },
  {
    code: 'JO',
    name: 'Jordan',
    emoji: '🇯🇴',
    unicode: 'U+1F1EF U+1F1F4',
    continent: 'Asia',
    tags: ['jordan', 'jordanian'],
  },

  // Africa
  {
    code: 'ZA',
    name: 'South Africa',
    emoji: '🇿🇦',
    unicode: 'U+1F1FF U+1F1E6',
    continent: 'Africa',
    tags: ['south africa', 'south african'],
  },
  {
    code: 'NG',
    name: 'Nigeria',
    emoji: '🇳🇬',
    unicode: 'U+1F1F3 U+1F1EC',
    continent: 'Africa',
    tags: ['nigeria', 'nigerian'],
  },
  {
    code: 'EG',
    name: 'Egypt',
    emoji: '🇪🇬',
    unicode: 'U+1F1EA U+1F1EC',
    continent: 'Africa',
    tags: ['egypt', 'egyptian'],
  },
  {
    code: 'MA',
    name: 'Morocco',
    emoji: '🇲🇦',
    unicode: 'U+1F1F2 U+1F1E6',
    continent: 'Africa',
    tags: ['morocco', 'moroccan'],
  },
  {
    code: 'KE',
    name: 'Kenya',
    emoji: '🇰🇪',
    unicode: 'U+1F1F0 U+1F1EA',
    continent: 'Africa',
    tags: ['kenya', 'kenyan'],
  },
  {
    code: 'GH',
    name: 'Ghana',
    emoji: '🇬🇭',
    unicode: 'U+1F1EC U+1F1ED',
    continent: 'Africa',
    tags: ['ghana', 'ghanaian'],
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    emoji: '🇪🇹',
    unicode: 'U+1F1EA U+1F1F9',
    continent: 'Africa',
    tags: ['ethiopia', 'ethiopian'],
  },
  {
    code: 'TN',
    name: 'Tunisia',
    emoji: '🇹🇳',
    unicode: 'U+1F1F9 U+1F1F3',
    continent: 'Africa',
    tags: ['tunisia', 'tunisian'],
  },

  // Oceania
  {
    code: 'AU',
    name: 'Australia',
    emoji: '🇦🇺',
    unicode: 'U+1F1E6 U+1F1FA',
    continent: 'Oceania',
    tags: ['australia', 'australian'],
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    emoji: '🇳🇿',
    unicode: 'U+1F1F3 U+1F1FF',
    continent: 'Oceania',
    tags: ['new zealand', 'kiwi'],
  },
  {
    code: 'FJ',
    name: 'Fiji',
    emoji: '🇫🇯',
    unicode: 'U+1F1EB U+1F1EF',
    continent: 'Oceania',
    tags: ['fiji', 'fijian'],
  },

  // South America
  {
    code: 'BR',
    name: 'Brazil',
    emoji: '🇧🇷',
    unicode: 'U+1F1E7 U+1F1F7',
    continent: 'South America',
    tags: ['brazil', 'brazilian'],
  },
  {
    code: 'AR',
    name: 'Argentina',
    emoji: '🇦🇷',
    unicode: 'U+1F1E6 U+1F1F7',
    continent: 'South America',
    tags: ['argentina', 'argentinian'],
  },
  {
    code: 'CL',
    name: 'Chile',
    emoji: '🇨🇱',
    unicode: 'U+1F1E8 U+1F1F1',
    continent: 'South America',
    tags: ['chile', 'chilean'],
  },
  {
    code: 'CO',
    name: 'Colombia',
    emoji: '🇨🇴',
    unicode: 'U+1F1E8 U+1F1F4',
    continent: 'South America',
    tags: ['colombia', 'colombian'],
  },
  {
    code: 'PE',
    name: 'Peru',
    emoji: '🇵🇪',
    unicode: 'U+1F1F5 U+1F1EA',
    continent: 'South America',
    tags: ['peru', 'peruvian'],
  },
  {
    code: 'VE',
    name: 'Venezuela',
    emoji: '🇻🇪',
    unicode: 'U+1F1FB U+1F1EA',
    continent: 'South America',
    tags: ['venezuela', 'venezuelan'],
  },
  {
    code: 'EC',
    name: 'Ecuador',
    emoji: '🇪🇨',
    unicode: 'U+1F1EA U+1F1E8',
    continent: 'South America',
    tags: ['ecuador', 'ecuadorian'],
  },
  {
    code: 'UY',
    name: 'Uruguay',
    emoji: '🇺🇾',
    unicode: 'U+1F1FA U+1F1FE',
    continent: 'South America',
    tags: ['uruguay', 'uruguayan'],
  },
];

export type FlagCode = (typeof flagsData)[number]['code'];
